services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/zookeeper/data
      - zookeeper_log:/zookeeper/log
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.6.0
    restart: unless-stopped
    volumes:
      - kafka_data:/kafka/data
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      # KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 10485880

  vault:
    image: hashicorp/vault:latest
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: testtoken
    ports:
      - 8200:8200
    privileged: true
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: myuser1
      POSTGRES_PASSWORD: ${DB_PSW}
      POSTGRES_DB: penguinsDB
    ports:
      - 5432:5432
  web:
    build: .
    command: bash -c "python src/api/test_vault.py && fastapi dev src/api/api.py --host 0.0.0.0 --port 8012"
    ports:
      - 8012:8012
    image: borisvikvik/borisvikvik-penguins-data-science:4_lab
    depends_on:
      - db
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  zookeeper_data:
  zookeeper_log:
  kafka_data: